### ISSUE TITLE
[Severe Bug] Duplicated Eggs

### ISSUE THREAD

**Issue by Trip-Trap** [Thy-Vipe/BeastsOfBermuda-issues#105]
*Expected Results:* After a crash/restart for eggs to not duplicate.
*Actual Results:* If a server crashes/restarts eg*gs that were possessed by a player will duplicate. They have the same pawn ID which results in lots of issues, including for creatures disappearing after returning to creature select, not being assined to the correct owner after death or having the wrong steam ID.
*Replication:* Make an egg, stay in it for 2 minutes, or force server save, crash the server. There now will be two eggs with the same pawn ID. The duplicate does not show up with Toggle Player Name Tags.

**Comment by Trip-Trap** [comment]
Could not summit it through the reporter bc "something went wrong"

**Comment by Thy-Vipe** [comment]
I think I have a hunch on why it happens. The egg gets saved twice. The first time, through it being an actor. The second, via the "save me" function. (Saves a player and their pawn). That would append the data twice. I wouldn't be surprised if something similar can be done by possessing an egg, leaving it, then possessing it again, and restart the server.  That is because, eggs arent treated as unique entities, that way they can spawn when the server loads up. Perhaps there's improvements to do there. I'll likely make it so that entities that can't be "attached" to a player (eggs) won't save via the save me function.

**Comment by Thy-Vipe** [comment]
I have a potential fix for it for the next patch.

**Comment by Predatoria** [comment]
Tested and verified to be fixed on tester!
