### ISSUE TITLE
[Bug] combat log dock broken

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#1072]
_Originally written by **iBradley | 76561198981287444**_
Game Version: 1.1.1029

*===== System Specs =====
CPU Brand: AMD Ryzen 5 3600 6-Core Processor              
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce GTX 1660 SUPER
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

*Expected Results:* to undock the combat log
*Actual Results:* undocked it and when resized it wont allow me to dock again 
*Replication:*

**Comment by Trip-Trap** [comment]
Resizing the combat log def is buggy. When i click on the white square to resize it, it moves the window around but i cant let go of it when clicking again. Meaning my cursor is stuck resizing the window. (on additional note, if you happen to put the "dock" option behind chat when you return to creature slot selection it wont let you click the button through chat)
It also didnt give me the cursor back after returning to creature slot selection and was only able to bring it up when hitting tab for the player list - and opening playerlist in creature slot selection is usually not even possible.

Video of behaviour:
https://youtu.be/h_4SjsXpGm4
Another bug with the combat log that happens if you click on the white button without the log being undocked:
https://youtu.be/3J7LrHDftCc

**Comment by Trip-Trap** [comment]
#3061
