### ISSUE TITLE
[Bug] Friendship option

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#125]
_Originally written by **Alather | 76561198153501420**_
Game Version: 1.1.946

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

Can't apply any settings to the friendship thing which can be found under options. I've tried about anything, but everytime I've applied the desired settings, the friendship goes back to blank.

**Comment by Predatoria** [comment]
This was noticed on tester a while back, but I'm not sure how to fix it globally.  It's caused by an old save file on steam cloud coming in and overwriting the local copy of the save data.  

To fix this:

Disable steam cloud
Delete the old save file with this data in it.
Save it.
Reenable steam cloud.
