### ISSUE TITLE
[Quality of life] Egg request popping up in other languages

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#292]
_Originally written by **Stormy H Temptess | 76561198163272695**_
Game Version: 1.1.955

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 970
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Context: **Rival shores, up near the cold Mountain top-** 
Map: Rival_Shores

So I bred with a female and got the egg request in what i think was German, i'm like a second generation Para and so is she.

**Comment by cleafspear** [comment]
is this related to the server locale overriding the client locale on some prompts?

**Comment by Predatoria** [comment]
This should be fixed after Vipe's rework of the invite and request code.  It was being caused because we were previously sending translated strings across the network, and they were generated server-side.  I believe Vipe's new implementation of this system does not have this issue.  I'm going to mark this as closed due to the code rework.
