### ISSUE TITLE
[Bug] Ory combat mode 

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3769]
_Originally written by **Egg Dog | 76561198029200412**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1080
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Map: Rival_Shores

when i switch to combat mode in the burrow, it will change automatic to dig mode without showing me the dirt inventory in the hud . that make fighting in burrow very tricky

**Comment by TeaTimeJess** [comment]
Confirmed, after a growth tick Ory will automatically shift out of attack stance back to burrowing stance but not bring up the digging UI.

- Spawn in as Ory
- Create a burrow
- Enter and stay inside burrow
- Switch to attack stance
- Wait for growth tick
- Attempt to attack
- Ory will dig instead of attack.

**Comment by Predatoria** [comment]
This was happening on the growth tick.  It should be fixed next tester patch.

**Comment by cleafspear** [comment]
resolved
