### ISSUE TITLE
[Bug] Rex Charge walk bug

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#3872]
_Originally written by **1GuyWithCookies | 76561198414659059**_
Game Version: 1.1.1128

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1050
GPU Driver Info: Unknown
Num CPU Cores: 4
===================*
Map: Rival_Shores

If you start sneak and sniff you can walk without losing charge

**Comment by TeaTimeJess** [comment]
Unable to reproduce, when crouching to charge the ability then activating sniff after, the charge resets after the micro-adjustment setting is reached after ~1s of moving.

**Comment by Trip-Trap** [comment]
Sniffing doesnt seem to be do anything. 
I tried around as a fresh spawn on flat terrain&slighthly uneven terrain on Test Performance. Sometimes it just seem to be allowing you not to lose the DA even tho you are moving at crouch speed. (maybe since the movement number seem to be inconsistent especially when you turn while moving DA or quickly uncrouch and crouch again) But in no way is it letting me use normal walk without losing DA
