### ISSUE TITLE
[Bug] FPS Drop when eating foliage

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#40]
_Originally written by **Gavin | 76561198254999852**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Vendor: GenuineIntel
GPU Brand: NVIDIA GeForce GTX 1070
GPU Driver Info: Unknown
Num CPU Cores: 6
===================*
Context: **Herbivore** 

*Expected Results:* Smooth FPS and no stutters while dinosaurs pick up/eat ferns and trees.
*Actual Results:* FPS drops and stutters when a dinosaur picks up/eats ferns and trees. Especially bad on Snowy Mountain in RS.
*Replication:* Have an apato pick up a tree or eat a few trees and there may be FPS drops and stutters.

**Comment by Predatoria** [comment]
I'm going to take a look at this and profile it in UE.  After our optimizations to foliage that specifically addressed the hitch associated with moving ISMC instances during runtime, I'm surprised to see this report.

**Comment by Predatoria** [comment]
I was able to reproduce the FPS hitch.  It happens when held foliage bundles are placed down.  The root balls were not properly set to have no collision, and it was causing the collision for the ISMC's on the scene to redraw.  

Setting these to have no collision has fixed this in PIE.  I'm marking it as potentially fixed.

**Comment by Predatoria** [comment]
Confirmed as fixed on tester
