### ISSUE TITLE
[Bug] Spawning in above ground after a server crashed in flood

### ISSUE THREAD

**Issue by BoB-Client** [Thy-Vipe/BeastsOfBermuda-issues#60]
_Originally written by **Man Ray | 76561198010746906**_
Game Version: 1.1.938

*===== System Specs =====
CPU Brand: AMD Ryzen 7 2700 Eight-Core Processor          
Vendor: AuthenticAMD
GPU Brand: NVIDIA GeForce RTX 2060
GPU Driver Info: Unknown
Num CPU Cores: 8
===================*
the server crashed while in a flood, when i logg back in my mosasaur fell out of the air...i have recording if interested this happen on 6 14 2020 at 11:08 the dinosaur was mosasaur 1.222

**Comment by Trip-Trap** [comment]
This is a general issue for aquatics spawning back in. They will spawn mid air (since the flood water had been there before or the tide had been higher) and then fall&receive the fall damage. Its also not aquatic exclusive, everything that spawns mid-air will fall and die (except ptera if the player is fast enough to hit space to fly ofc).
Probably only solution is to put creatures on the next hit point bellow them and then spawn them in, water surface considered as a hit point as well. But that is probably not doable.

**Comment by Predatoria** [comment]
We won't be fixing this.  We'd rather fix the server crashes.  Marking as will not fix and closing.
